"""
Obsidian synthesize — generate a LLM synthesis note across all notes
related to a given topic, using embeddings similarity to find candidates.
Usage:
    synthesize(topic, config, state_db, embeddings_db, llm)
Workflow:
  1. find_similar_chunks(topic, top_k=30, dedupe_by_paper=True) → chunk results
     Falls back to find_similar_to_text(topic, top_k=15) when no chunks exist.
  2. Load extraction_json + note title for each unique paper DOI
  3. Ask LLM to write a synthesis paragraph (chunk passage included for context)
  4. Write to Literature/Connections/{slug}.md (or update if exists)
The synthesis note preserves any user-edited content outside the
generated section (it uses a simple header boundary, not persist zones).
"""
from __future__ import annotations

import json
import logging
import re
from datetime import date
from pathlib import Path
from typing import Any

from scripts.llm.prompt_registry import load_prompt
from scripts.llm.prompt_safety import sanitize_for_prompt

logger = logging.getLogger(__name__)
_SYNTHESIS_TEMPLATE = """\
---
topic: "{topic}"
generated: "{run_date}"
source_count: {n_sources}
---
# Synthesis: {topic}
> *Auto-generated by `lit-monitor obsidian synthesize`*
> *Sources: {n_sources} notes · Generated {run_date}*
{synthesis_text}
## Sources
{source_list}
---
*Last updated: {run_date}*
"""
def synthesize(
    topic: str,
    config,
    state_db,
    embeddings_db,
    llm,
    top_k: int = 15,
    connections_folder: str | None = None,
    rag_mode: str | None = None,
    graph_db=None,
) -> str:
    """
    Generate and write a synthesis note for the given topic.
    Parameters
    ----------
    topic:
        Free-text topic description (used as ChromaDB query string).
    config:
        Config object.
    state_db:
        StateDB instance.
    embeddings_db:
        EmbeddingsDB instance.
    llm:
        LLMClient instance.
    top_k:
        Number of similar notes to synthesize across.
    connections_folder:
        Override for the vault connections folder path.
    rag_mode:
        One of "vector", "graph", "hybrid". Default reads from
        config.retrieval.default_mode; falls back to "vector".
    graph_db:
        Optional GraphDB instance; required for graph/hybrid modes.
    Returns
    -------
    str: Path to the written synthesis note.
    """
    # G9: resolve rag_mode; default from config, fallback "vector".
    _cfg_mode = (
        getattr(getattr(config, "retrieval", None), "default_mode", "vector")
        if config is not None else "vector"
    )
    _rag_mode = rag_mode or _cfg_mode or "vector"

    _reranker_cfg = getattr(config, "reranker", None)

    if _rag_mode == "vector":
        # 1. Find similar passages — chunk-level first, paper-level fallback.
        # Existing path unchanged (preserves v0.3.3 behaviour).
        chunk_results = embeddings_db.find_similar_chunks(
            topic,
            top_k=top_k * 2,
            dedupe_by_paper=True,
            rerank_with_query=topic,
            reranker_config=_reranker_cfg,
        )
        use_chunks = bool(chunk_results)
        if use_chunks:
            similar = chunk_results
        else:
            logger.debug(
                "No chunks indexed yet — falling back to paper-level similarity for topic %r",
                topic,
            )
            similar = embeddings_db.find_similar_to_text(
                topic,
                top_k=top_k,
                rerank_with_query=topic,
                reranker_config=_reranker_cfg,
            )
    else:
        # G9: graph or hybrid — query expansion + graph/hybrid retrieval.
        expanded_terms = _expand_query(topic, llm)
        # Build entity_ids from expanded surface forms via graph resolve, if possible.
        entity_ids = _resolve_entity_ids(expanded_terms, graph_db)
        from scripts.retrieval.branch import retrieve_doi_candidates
        # W1: forward exclude_id (None here — synthesize has no seed paper) and
        # reranker config so the vector leg of hybrid preserves v0.3.3 behaviour.
        doi_candidates = retrieve_doi_candidates(
            _rag_mode,
            query_text=topic,          # vector leg uses the raw topic
            entity_ids=entity_ids,     # graph leg uses resolved entity IDs
            embeddings_db=embeddings_db,
            graph_db=graph_db,
            k=top_k * 2,
            rerank_with_query=topic if _rag_mode == "hybrid" else None,
            reranker_config=_reranker_cfg if _rag_mode == "hybrid" else None,
        )
        # Convert (doi, score) pairs → ChromaDB-style result dicts.
        # C3: hydrate ``document`` from state_db so the cross-encoder reranker
        # actually scores meaningful text instead of empty strings.
        similar = []
        for d, s in doi_candidates[:top_k]:
            record = state_db.get_paper(d) if hasattr(state_db, "get_paper") else None
            record = record or {}
            similar.append({
                "id": d,
                "score": s,
                "document": _build_reranker_document(record),
                "metadata": {"note_title": record.get("note_title", ""), "doi": d},
            })
        # C1: reranker chain at the END — use the real cross-encoder helper
        # (``_apply_reranker``); the previous ``from scripts.output.reranker
        # import rerank`` raised ImportError and was silently swallowed.
        if _reranker_cfg and similar:
            from scripts.output.embeddings import _apply_reranker, _reranker_enabled
            if _reranker_enabled(_reranker_cfg):
                similar = _apply_reranker(topic, similar, top_k, _reranker_cfg)
        use_chunks = False  # no chunk-level passages in graph/hybrid mode
    if not similar:
        logger.warning("No similar notes found for topic %r", topic)
        return ""
    # 2. Load extractions — resolve DOI from chunk metadata or direct id
    source_summaries: list[dict[str, Any]] = []
    for result in similar[:top_k]:
        if use_chunks:
            doi = result.get("metadata", {}).get("doi", "")
            passage = result.get("document", "")
            section = result.get("metadata", {}).get("section_heading", "")
        else:
            doi = result.get("id", "")
            passage = ""
            section = ""
        if not doi:
            continue
        record = state_db.get_paper(doi)
        if not record:
            continue
        extraction = json.loads(record.get("extraction_json") or "{}")
        note_title = record.get("note_title", doi)
        title = record.get("title", "")
        source_type = record.get("source_type", "paper")
        source_summaries.append({
            "note_title": note_title,
            "title": title,
            "source_type": source_type,
            "core_finding": extraction.get("core_finding") or extraction.get("chapter_summary") or "",
            "methods_summary": extraction.get("methods_summary") or extraction.get("methods_or_frameworks") or "",
            "score": result.get("score", 0.0),
            # chunk-level extras surfaced in the prompt for richer context
            "passage": passage[:600] if passage else "",
            "section_heading": section,
        })
    if not source_summaries:
        logger.warning("No extractable summaries for topic %r", topic)
        return ""
    # 3. Build LLM prompt
    n_sources = len(source_summaries)
    prompt = load_prompt("synthesis")
    sources_text = _format_sources(source_summaries)
    user_prompt = prompt.render_user(topic=sanitize_for_prompt(topic), n_sources=n_sources, sources=sources_text)
    # 4. Generate synthesis
    try:
        raw = llm.complete(prompt.system, user_prompt, max_tokens=prompt.max_tokens)
        synthesis_text = raw.strip()

    except Exception as exc:
        logger.error("LLM synthesis failed for topic %r: %s", topic, exc)
        synthesis_text = f"*Synthesis generation failed: {exc}*"
    # 5. Write note
    run_date = str(date.today())
    source_list = "\n".join(
        f"- [[{s['note_title']}]] — {s['title']} (score: {s['score']:.3f})"
        for s in source_summaries
    )
    content = _SYNTHESIS_TEMPLATE.format(
        topic=topic,
        run_date=run_date,
        n_sources=n_sources,
        synthesis_text=synthesis_text,
        source_list=source_list,
    )
    note_path = _write_synthesis_note(topic, content, config, connections_folder)
    logger.info("Synthesis note written: %s", note_path)
    return note_path
def _format_sources(source_summaries: list[dict[str, Any]]) -> str:
    """Format source summaries as a numbered list for the synthesis prompt.

    Every untrusted field (note_title, title, extraction fields, ChromaDB chunk
    text, section heading) is passed through ``sanitize_for_prompt`` before
    being interpolated into the prompt.  Structural labels (``Title:``,
    ``Core finding:`` etc.) come from this function's own source and are
    therefore not sanitised — they are trusted.  Audit 29 closed a sibling
    of the B2 fix here: the previous version sanitised ``topic=`` at the
    ``render_user`` call site but left this function's output unscrubbed.
    """
    lines: list[str] = []
    for i, s in enumerate(source_summaries, 1):
        note_title = sanitize_for_prompt(s.get("note_title", ""))
        title = sanitize_for_prompt(s.get("title", ""))
        source_type = sanitize_for_prompt(s.get("source_type", "paper"))
        core = sanitize_for_prompt((s.get("core_finding") or "")[:400])
        methods = sanitize_for_prompt((s.get("methods_summary") or "")[:200])
        passage = sanitize_for_prompt((s.get("passage") or "").strip())
        section = sanitize_for_prompt((s.get("section_heading") or "").strip())
        entry = (
            f"{i}. [[{note_title}]] ({source_type})\n"
            f"   Title: {title}\n"
            f"   Core finding: {core}\n"
            f"   Methods: {methods}\n"
        )
        if passage:
            section_note = f" [{section}]" if section else ""
            entry += f"   Relevant passage{section_note}: {passage}\n"
        lines.append(entry)
    return "\n".join(lines)
def _write_synthesis_note(
    topic: str,
    content: str,
    config,
    connections_folder: str | None,
) -> str:
    vault_path = Path(config.obsidian.vault_path)
    folder_rel = connections_folder or getattr(
        config.obsidian, "connections_folder", "Literature/Connections"
    )
    folder = vault_path / folder_rel
    folder.mkdir(parents=True, exist_ok=True)
    slug = _slugify(topic)
    note_path = folder / f"Synthesis_{slug}.md"
    # Preserve user content below the generated section if file exists
    if note_path.exists():
        existing = note_path.read_text(encoding="utf-8")
        user_section = _extract_user_section(existing)
        if user_section:
            content = content.rstrip("\n") + "\n\n## Notes\n" + user_section

    note_path.write_text(content, encoding="utf-8")
    return str(note_path)
def _extract_user_section(content: str) -> str:
    """
    Return any text after the last '---' divider line in a synthesis note,
    which is where user-added notes live.
    """
    parts = content.rsplit("\n---\n", 1)
    if len(parts) == 2:
        after = parts[1].strip()
        # Strip the auto-generated "Last updated:" line
        after = re.sub(r"^\*Last updated:.*\*\s*", "", after)
        return after.strip()
    return ""
def _slugify(text: str) -> str:
    """Convert a topic string to a safe filename slug."""
    slug = re.sub(r"[^\w\s-]", "", text)
    slug = re.sub(r"[\s_]+", "_", slug.strip())
    return slug[:60]


# ---------------------------------------------------------------------------
# G9 C3: Reranker document hydration
# ---------------------------------------------------------------------------

def _build_reranker_document(record: dict) -> str:
    """Build the passage string the cross-encoder reranker scores against.

    Mirrors ``_paper_embed_text`` in brain_build: title + abstract +
    core_finding (the same fields used to build the paper-level embedding in
    v0.3.3). Returns "" only when every field is missing.
    """
    if not record:
        return ""
    title = (record.get("title") or "").strip()
    abstract = ""
    core_finding = ""
    extraction_raw = record.get("extraction_json") or ""
    if extraction_raw:
        try:
            extraction = json.loads(extraction_raw)
        except Exception:
            extraction = {}
        abstract = (extraction.get("abstract") or "").strip()
        core_finding = (extraction.get("core_finding") or "").strip()
    parts = [p for p in (title, abstract, core_finding) if p]
    return " ".join(parts)


# ---------------------------------------------------------------------------
# G9: Query expansion helpers
# ---------------------------------------------------------------------------

def _expand_query(topic: str, llm) -> list[str]:
    """G9: expand a topic string into up to 5 related surface forms.

    Calls the LLM with the prompt loaded from config/prompts/query_expansion.yaml.
    On any failure (LLM unavailable, bad JSON, etc.) logs a WARN and falls back
    to returning [topic] so the graph retrieval can still proceed with the
    original topic string.

    Args:
        topic: The raw topic string from the user.
        llm:   Any LLMClient instance (or None).

    Returns:
        List of up to 5 string surface forms (always non-empty).
    """
    if llm is None:
        logger.warning(
            "Query expansion skipped: no LLM client available. Using topic-only: %r", topic
        )
        return [topic]
    try:
        prompt = load_prompt("query_expansion")
        user_msg = prompt.render_user(topic=topic)
        raw_response = llm.complete(prompt.system, user_msg, max_tokens=prompt.max_tokens)
        expanded = json.loads(raw_response)
        if isinstance(expanded, list) and expanded:
            terms = [str(s) for s in expanded[:5] if s]
            logger.info("G9 query expansion for %r: %r", topic, terms)
            return terms if terms else [topic]
    except Exception as exc:
        logger.warning(
            "Query expansion failed; falling back to topic-only: %s", exc
        )
    return [topic]


def _resolve_entity_ids(surface_forms: list[str], graph_db) -> list[str]:
    """G9: resolve surface form strings to canonical entity IDs via graph_db.

    Uses graph_db.resolve_query_entity() when available (G7). Returns an empty
    list when the graph is unavailable or nothing resolves — callers MUST treat
    surface forms (free text) as distinct from canonical entity IDs because
    find_papers_by_entities expects IDs that exist in the graph.

    Args:
        surface_forms: List of term strings (output of _expand_query).
        graph_db:      GraphDB instance or None.

    Returns:
        List of canonical entity ID strings (may be empty).
    """
    if graph_db is None or not surface_forms:
        # W3: return [] on no-match instead of leaking surface forms as if they
        # were entity IDs — find_papers_by_entities silently produces zero hits
        # when given free-text terms, which masks the graph-unavailable case.
        return []
    canonical: list[str] = []
    for term in surface_forms:
        try:
            result = graph_db.resolve_query_entity(term)
        except Exception as exc:
            logger.debug("Entity resolution failed for %r: %s", term, exc)
            continue
        if not result:
            continue
        # W2: resolve_query_entity returns a (entity_id, canonical_name, score)
        # tuple in current G7 contract. Accept either a single tuple or a list
        # of tuples — earlier code branched on str too, which the real API
        # never returns; drop that dead branch.
        items = result if isinstance(result, list) else [result]
        for item in items:
            if isinstance(item, tuple) and item:
                canonical.append(str(item[0]))
    # De-duplicate while preserving order.
    seen: set[str] = set()
    unique: list[str] = []
    for c in canonical:
        if c not in seen:
            seen.add(c)
            unique.append(c)
    return unique
