"""
Obsidian synthesize — generate a LLM synthesis note across all notes
related to a given topic, using embeddings similarity to find candidates.
Usage:
    synthesize(topic, config, state_db, embeddings_db, llm)
Workflow:
  1. find_similar_chunks(topic, top_k=30, dedupe_by_paper=True) → chunk results
     Falls back to find_similar_to_text(topic, top_k=15) when no chunks exist.
  2. Load extraction_json + note title for each unique paper DOI
  3. Ask LLM to write a synthesis paragraph (chunk passage included for context)
  4. Write to Literature/Connections/{slug}.md (or update if exists)
The synthesis note preserves any user-edited content outside the
generated section (it uses a simple header boundary, not persist zones).
"""
from __future__ import annotations

import json
import logging
import re
from datetime import date
from pathlib import Path
from typing import Any

from scripts.llm.prompt_registry import load_prompt
from scripts.llm.prompt_safety import sanitize_for_prompt

logger = logging.getLogger(__name__)
_SYNTHESIS_TEMPLATE = """\
---
topic: "{topic}"
generated: "{run_date}"
source_count: {n_sources}
---
# Synthesis: {topic}
> *Auto-generated by `lit-monitor obsidian synthesize`*
> *Sources: {n_sources} notes · Generated {run_date}*
{synthesis_text}
## Sources
{source_list}
---
*Last updated: {run_date}*
"""
def synthesize(
    topic: str,
    config,
    state_db,
    embeddings_db,
    llm,

    top_k: int = 15,
    connections_folder: str | None = None,
) -> str:
    """
    Generate and write a synthesis note for the given topic.
    Parameters
    ----------
    topic:
        Free-text topic description (used as ChromaDB query string).
    config:
        Config object.
    state_db:
        StateDB instance.
    embeddings_db:
        EmbeddingsDB instance.
    llm:
        LLMClient instance.
    top_k:
        Number of similar notes to synthesize across.
    connections_folder:
        Override for the vault connections folder path.
    Returns
    -------
    str: Path to the written synthesis note.
    """
    # 1. Find similar passages — chunk-level first, paper-level fallback
    _reranker_cfg = getattr(config, "reranker", None)
    chunk_results = embeddings_db.find_similar_chunks(
        topic,
        top_k=top_k * 2,
        dedupe_by_paper=True,
        rerank_with_query=topic,
        reranker_config=_reranker_cfg,
    )
    use_chunks = bool(chunk_results)
    if use_chunks:
        similar = chunk_results
    else:
        logger.debug("No chunks indexed yet — falling back to paper-level similarity for topic %r", topic)
        similar = embeddings_db.find_similar_to_text(
            topic,
            top_k=top_k,
            rerank_with_query=topic,
            reranker_config=_reranker_cfg,
        )
    if not similar:
        logger.warning("No similar notes found for topic %r", topic)
        return ""
    # 2. Load extractions — resolve DOI from chunk metadata or direct id
    source_summaries: list[dict[str, Any]] = []
    for result in similar[:top_k]:
        if use_chunks:
            doi = result.get("metadata", {}).get("doi", "")
            passage = result.get("document", "")
            section = result.get("metadata", {}).get("section_heading", "")
        else:
            doi = result.get("id", "")
            passage = ""
            section = ""
        if not doi:
            continue
        record = state_db.get_paper(doi)
        if not record:
            continue
        extraction = json.loads(record.get("extraction_json") or "{}")
        note_title = record.get("note_title", doi)
        title = record.get("title", "")
        source_type = record.get("source_type", "paper")
        source_summaries.append({
            "note_title": note_title,
            "title": title,
            "source_type": source_type,
            "core_finding": extraction.get("core_finding") or extraction.get("chapter_summary") or "",
            "methods_summary": extraction.get("methods_summary") or extraction.get("methods_or_frameworks") or "",
            "score": result.get("score", 0.0),
            # chunk-level extras surfaced in the prompt for richer context
            "passage": passage[:600] if passage else "",
            "section_heading": section,
        })
    if not source_summaries:
        logger.warning("No extractable summaries for topic %r", topic)
        return ""
    # 3. Build LLM prompt
    n_sources = len(source_summaries)
    prompt = load_prompt("synthesis")
    sources_text = _format_sources(source_summaries)
    user_prompt = prompt.render_user(topic=sanitize_for_prompt(topic), n_sources=n_sources, sources=sources_text)
    # 4. Generate synthesis
    try:
        raw = llm.complete(prompt.system, user_prompt, max_tokens=prompt.max_tokens)
        synthesis_text = raw.strip()

    except Exception as exc:
        logger.error("LLM synthesis failed for topic %r: %s", topic, exc)
        synthesis_text = f"*Synthesis generation failed: {exc}*"
    # 5. Write note
    run_date = str(date.today())
    source_list = "\n".join(
        f"- [[{s['note_title']}]] — {s['title']} (score: {s['score']:.3f})"
        for s in source_summaries
    )
    content = _SYNTHESIS_TEMPLATE.format(
        topic=topic,
        run_date=run_date,
        n_sources=n_sources,
        synthesis_text=synthesis_text,
        source_list=source_list,
    )
    note_path = _write_synthesis_note(topic, content, config, connections_folder)
    logger.info("Synthesis note written: %s", note_path)
    return note_path
def _format_sources(source_summaries: list[dict[str, Any]]) -> str:
    """Format source summaries as a numbered list for the synthesis prompt.

    Every untrusted field (note_title, title, extraction fields, ChromaDB chunk
    text, section heading) is passed through ``sanitize_for_prompt`` before
    being interpolated into the prompt.  Structural labels (``Title:``,
    ``Core finding:`` etc.) come from this function's own source and are
    therefore not sanitised — they are trusted.  Audit 29 closed a sibling
    of the B2 fix here: the previous version sanitised ``topic=`` at the
    ``render_user`` call site but left this function's output unscrubbed.
    """
    lines: list[str] = []
    for i, s in enumerate(source_summaries, 1):
        note_title = sanitize_for_prompt(s.get("note_title", ""))
        title = sanitize_for_prompt(s.get("title", ""))
        source_type = sanitize_for_prompt(s.get("source_type", "paper"))
        core = sanitize_for_prompt((s.get("core_finding") or "")[:400])
        methods = sanitize_for_prompt((s.get("methods_summary") or "")[:200])
        passage = sanitize_for_prompt((s.get("passage") or "").strip())
        section = sanitize_for_prompt((s.get("section_heading") or "").strip())
        entry = (
            f"{i}. [[{note_title}]] ({source_type})\n"
            f"   Title: {title}\n"
            f"   Core finding: {core}\n"
            f"   Methods: {methods}\n"
        )
        if passage:
            section_note = f" [{section}]" if section else ""
            entry += f"   Relevant passage{section_note}: {passage}\n"
        lines.append(entry)
    return "\n".join(lines)
def _write_synthesis_note(
    topic: str,
    content: str,
    config,
    connections_folder: str | None,
) -> str:
    vault_path = Path(config.obsidian.vault_path)
    folder_rel = connections_folder or getattr(
        config.obsidian, "connections_folder", "Literature/Connections"
    )
    folder = vault_path / folder_rel
    folder.mkdir(parents=True, exist_ok=True)
    slug = _slugify(topic)
    note_path = folder / f"Synthesis_{slug}.md"
    # Preserve user content below the generated section if file exists
    if note_path.exists():
        existing = note_path.read_text(encoding="utf-8")
        user_section = _extract_user_section(existing)
        if user_section:
            content = content.rstrip("\n") + "\n\n## Notes\n" + user_section

    note_path.write_text(content, encoding="utf-8")
    return str(note_path)
def _extract_user_section(content: str) -> str:
    """
    Return any text after the last '---' divider line in a synthesis note,
    which is where user-added notes live.
    """
    parts = content.rsplit("\n---\n", 1)
    if len(parts) == 2:
        after = parts[1].strip()
        # Strip the auto-generated "Last updated:" line
        after = re.sub(r"^\*Last updated:.*\*\s*", "", after)
        return after.strip()
    return ""
def _slugify(text: str) -> str:
    """Convert a topic string to a safe filename slug."""
    slug = re.sub(r"[^\w\s-]", "", text)
    slug = re.sub(r"[\s_]+", "_", slug.strip())
    return slug[:60]
