"""Shared discovery-digest renderer.

Single source of truth for the Markdown digest format produced by:
- ``lit-monitor discovery export-md`` (CLI export path)
- ``_write_digest()`` in ``scripts/pipelines/discovery.py`` (auto-write path)

``render_digest`` absorbs the full auto-write format introduced in Phase 5:
YAML frontmatter, a "Top Results" section (papers at or above sim_threshold),
an "All New Results" section, and an optional "Pipeline Run Summary" prefix.

Field-name conventions
----------------------
The pipeline populates paper dicts with ``similarity_score`` / ``llm_rationale``
/ ``authors`` / ``year``.  The CLI export path historically used ``score`` /
``rationale``.  ``render_digest`` accepts both — pipeline names take priority
over the shorter CLI aliases so that a single dict shape works across callers.
"""
from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

_DEFAULT_SIM_THRESHOLD = 0.3
_DEFAULT_N_DATABASES = 5  # 4 primary + 1 S2 supplementary (kept as a safe fallback)


def render_digest(
    run: dict[str, Any],
    papers: list[dict[str, Any]],
    *,
    sim_threshold: float = _DEFAULT_SIM_THRESHOLD,
    n_databases: int | None = None,
    recent_runs: list[dict] | None = None,
    show_score_decomposition: bool = False,
    _today: str | None = None,
) -> str:
    """Render a discovery run as a Markdown digest note.

    Args:
        run:           Discovery run metadata dict.  Recognised keys:
                       ``run_date`` (ISO date string, preferred),
                       ``started_at`` (ISO datetime, fallback).
                       Either can supply today's date for the digest header.
        papers:        Ranked list of paper dicts.  Pipeline field names
                       (``similarity_score``, ``llm_rationale``, ``authors``,
                       ``year``) take priority over CLI aliases (``score``,
                       ``rationale``).
        sim_threshold: Papers with ``similarity_score >= sim_threshold`` appear
                       in the *Top Results* section.  Default 0.3.
        n_databases:   Number of databases searched.  Shown in the subtitle
                       line.  Defaults to ``_DEFAULT_N_DATABASES``.
        recent_runs:   If provided, a *Pipeline Run Summary* section is
                       prepended before the main digest body (L2 feature).
        show_score_decomposition:
                       Bundle B — when True, render a compact Markdown table of
                       per-signal score contributions after each paper's rationale.
                       Maps to ``digest.score_decomposition.show_in_md`` in config.
                       Default False → v0.8 / Bundle A behavior unchanged.
        _today:        Override the date string used in the output.  Pass a
                       fixed ISO date string (``"YYYY-MM-DD"``) in tests so
                       the output is deterministic.

    Returns:
        Markdown string.  Always ends with a trailing newline.
    """
    run_date = _resolve_run_date(run, _today)
    n_db = n_databases if n_databases is not None else _DEFAULT_N_DATABASES
    top_score = papers[0].get("similarity_score", papers[0].get("score", 0.0)) if papers else 0.0

    top_results = [
        p for p in papers
        if p.get("similarity_score", p.get("score", 0.0)) >= sim_threshold
    ]

    top_section = _format_paper_list(
        top_results[:20], include_rationale=True,
        show_score_decomposition=show_score_decomposition,
    )
    all_section = _format_paper_list(
        papers, include_rationale=False,
        show_score_decomposition=False,  # decomposition only in Top Results
    )

    content = (
        f'---\n'
        f'date: "{run_date}"\n'
        f'new_papers: {len(papers)}\n'
        f'top_similarity: {top_score:.3f}\n'
        f'---\n'
        f'# Discovery Digest — {run_date}\n'
        f'{len(papers)} new results found across {n_db} databases.\n'
        f'Similarity threshold: >{sim_threshold:.2f}\n'
        f'## Top Results\n'
        f'{top_section}\n'
        f'\n'
        f'## All New Results ({len(papers)})\n'
        f'{all_section}\n'
        f'---\n'
        f'*Generated by lit-monitor · {run_date}*\n'
    )

    if recent_runs:
        content = _format_pipeline_run_summary(recent_runs) + "\n---\n\n" + content

    return content


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _resolve_run_date(run: dict[str, Any], override: str | None) -> str:
    """Return the ISO date string for the digest header.

    Priority: explicit override → ``run["run_date"]`` → first 10 chars of
    ``run["started_at"]``.  Falls back to the empty string if nothing is set
    (callers should always provide at least one).
    """
    if override is not None:
        return override
    if run.get("run_date"):
        return str(run["run_date"])
    started = run.get("started_at") or ""
    return started[:10]


def _format_paper_list(
    papers: list[dict[str, Any]],
    *,
    include_rationale: bool,
    show_score_decomposition: bool = False,
) -> str:
    """Format a list of paper dicts as a Markdown bullet list.

    Accepts both pipeline field names (``similarity_score``, ``llm_rationale``,
    ``authors``, ``year``) and the shorter CLI aliases (``score``,
    ``rationale``).  Pipeline names take priority.

    Args:
        papers: Paper dicts.
        include_rationale: Append llm_rationale as a block quote when True.
        show_score_decomposition: Bundle B — when True, append a compact Markdown
            table of per-signal score contributions after the rationale for each
            paper that has a ``score_breakdown`` key.  Papers without the key are
            silently skipped (no table, no crash).
    """
    if not papers:
        return "*No results.*"
    lines = []
    for p in papers:
        doi = p.get("doi", "")
        title = p.get("title", "")
        authors = p.get("authors", [])
        year = p.get("year", "")
        # Pipeline name takes priority over CLI alias.
        score = p.get("similarity_score", p.get("score", 0.0))
        rationale = p.get("llm_rationale", p.get("rationale", ""))

        author_str = ", ".join(authors[:3]) if authors else ""
        if len(authors) > 3:
            author_str += " et al."

        doi_link = f"[DOI](https://doi.org/{doi})" if doi else ""
        line = f"- **{title}** · {author_str} ({year}) · score: {score:.3f}"
        if doi_link:
            line += f" · {doi_link}"
        if include_rationale and rationale:
            line += f"\n  > {rationale}"
        # Bundle B: opt-in per-paper breakdown table
        if show_score_decomposition:
            breakdown = p.get("score_breakdown")
            if breakdown:
                line += "\n" + _format_score_breakdown_table(breakdown, total=score)
        lines.append(line)
    return "\n".join(lines)


def _format_score_breakdown_table(
    breakdown: dict[str, float],
    total: float,
) -> str:
    """Bundle B: render a compact Markdown table for per-signal score contributions.

    Args:
        breakdown: Dict mapping signal name → float contribution.
        total:     The paper's overall similarity_score (shown in the total row).

    Returns:
        Markdown table string (indented 2 spaces for nesting inside a list item).

    Example output::

        | Signal | Score |
        |---|---|
        | vector | 0.847 |
        | domain_context | 0.123 |
        | **total** | **0.970** |
    """
    rows = ["| Signal | Score |", "|---|---|"]
    for signal, val in breakdown.items():
        rows.append(f"| {signal} | {val:.3f} |")
    rows.append(f"| **total** | **{total:.3f}** |")
    # Indent by 2 spaces so the table nests inside the bullet list item.
    return "\n".join("  " + r for r in rows)


def _format_pipeline_run_summary(recent_runs: list[dict]) -> str:
    """Format a Pipeline Run Summary section from run_log entries (L2)."""
    lines = ["## Pipeline Run Summary", ""]
    for run in recent_runs:
        run_type = run.get("run_type", "?")
        started = (run.get("started_at") or "")[:16].replace("T", " ")
        status = run.get("status", "?")
        processed = run.get("papers_processed", 0)
        failed = run.get("papers_failed", 0)
        lines.append(
            f"- **{run_type}** {started} — {status} "
            f"({processed} processed, {failed} failed)"
        )
    return "\n".join(lines) + "\n"
