"""
Vocabulary clustering — group canonical keywords into themes and write
a draft YAML file for human review.
Workflow:
1. `build_vocabulary(keywords, llm)` — sends canonical keyword list to the LLM
   in chunks and asks it to propose theme groupings → writes config/concepts_draft.yaml.
2. `map_keywords_to_themes(keywords, concepts)` — for each keyword string,
   returns the list of theme names it belongs to (fuzzy match against
   concepts.yaml theme keyword lists, threshold=0.75).
3. `flag_unmapped(keywords, concepts, threshold)` — returns keywords that
   don't match any theme above the threshold so they can be reviewed.
The user reviews concepts_draft.yaml, edits it, and saves as concepts.yaml
before the brain build (Phase 9).
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

import yaml

from scripts.llm.llm_client import LLMClient, parse_llm_json
from scripts.llm.prompt_registry import load_clustering_prompts
from scripts.llm.prompt_safety import sanitize_for_prompt

logger = logging.getLogger(__name__)

# Public so the CLI can reference the same path without hardcoding it twice.
CONCEPTS_DRAFT_PATH = Path("config/concepts_draft.yaml")

# Generated by clusters_to_topics_yaml() — human reviews and copies entries to
# topics.yaml.  Gitignored; never committed directly.
TOPICS_SUGGESTED_PATH = Path("config/topics_suggested.yaml")

# Fallback / hard-cap chunk size.  Smart sizing (N1, 2026-05-17) computes the
# actual chunk count from the LLM's num_ctx; this constant is used only as a
# safety floor / explicit hard cap when the user passes --chunk-size.
_CHUNK_SIZE = 60

# ── N1 smart-chunking constants (mirror extractor.py A6 math) ───────────────
_CHARS_PER_TOKEN: int = 4              # rule of thumb: English scientific text
_SAFETY_FACTOR: float = 0.75           # fraction of ctx to budget for input + output
_SYSTEM_PROMPT_RESERVE_TOKENS: int = 500   # system prompt overhead estimate
_FALLBACK_CTX: int = 8192              # build_vocabulary's traditional num_ctx
_MIN_KEYWORDS_PER_CHUNK: int = 20      # floor: never split below this; smaller chunks waste calls
_MAX_KEYWORDS_PER_CHUNK: int = 1000    # ceiling: even unlimited-context models cap here for sanity
_OUTPUT_MULTIPLIER: float = 1.5        # output JSON is roughly 1.5× input keyword text
_THEME_OVERHEAD_CHARS: int = 800       # ~10 themes × 80 chars each in JSON output

# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _chunk_list(items: list, size: int) -> list[list]:
    """Split a list into successive sublists of at most `size` items."""
    return [items[i : i + size] for i in range(0, len(items), size)]


def _keywords_per_chunk(
    llm: LLMClient,
    keywords: list[str],
    *,
    user_cap: int | None = None,
    chunk_chars_override: int | None = None,
) -> int:
    """Compute keywords-per-chunk from the LLM's num_ctx (N1 smart chunking).

    Mirrors A6's `_available_input_chars` budget math but solves for keyword count
    instead of returning a character budget.  The clustering prompt has roughly:

        input  ≈ K × (avg_len + 5)              [keywords with separator overhead]
        output ≈ K × avg_len × _OUTPUT_MULTIPLIER + _THEME_OVERHEAD_CHARS

    Budget: (num_ctx × _SAFETY_FACTOR − system_overhead) × _CHARS_PER_TOKEN
            ≥ input + output

    Solving for K and clamping by [_MIN_KEYWORDS_PER_CHUNK, _MAX_KEYWORDS_PER_CHUNK]
    plus any `user_cap` (the CLI `--chunk-size` hard cap).

    Parameters
    ----------
    llm:
        LLMClient instance with a `num_ctx` attribute (OllamaClient sets this
        from /api/show, num_ctx_override, or a fallback).
    keywords:
        The list of keywords being chunked; used to compute the average length.
    user_cap:
        Optional CLI override from `--chunk-size`.  When provided, the returned
        chunk size is at most this value.  Use 0 or None to skip the cap.
    chunk_chars_override:
        Optional per-mode override from `extraction.yaml build_vocabulary.chunk_chars`.
        When provided, used as the input-character budget directly; overrides
        the num_ctx-derived computation.

    Returns
    -------
    int
        Keyword count per chunk, clamped to safe bounds.
    """
    if not keywords:
        return _MIN_KEYWORDS_PER_CHUNK
    avg_len = sum(len(k) for k in keywords) / len(keywords)
    if chunk_chars_override is not None and chunk_chars_override > 0:
        budget_chars: float = float(chunk_chars_override)
    else:
        ctx = getattr(llm, "num_ctx", None) or _FALLBACK_CTX
        budget_chars = (
            (ctx * _SAFETY_FACTOR - _SYSTEM_PROMPT_RESERVE_TOKENS)
            * _CHARS_PER_TOKEN
        )
    # Each keyword costs (input chars + output chars) per chunk.
    per_keyword_cost = (avg_len + 5) + (avg_len * _OUTPUT_MULTIPLIER)
    if per_keyword_cost <= 0:
        # Defensive: average length of 0 is impossible after the empty-list check
        # above, but keep the math safe.
        raw_k = _MAX_KEYWORDS_PER_CHUNK
    else:
        raw_k = int((budget_chars - _THEME_OVERHEAD_CHARS) / per_keyword_cost)
    k = max(_MIN_KEYWORDS_PER_CHUNK, min(raw_k, _MAX_KEYWORDS_PER_CHUNK))
    if user_cap is not None and user_cap > 0:
        k = min(k, user_cap)
    logger.info(
        "_keywords_per_chunk: ctx=%s avg_kw_len=%.1f → %d keywords/chunk (user_cap=%s, override=%s)",
        getattr(llm, "num_ctx", None), avg_len, k, user_cap, chunk_chars_override,
    )
    return k


def _merge_clusters(base: dict, partial: dict) -> None:
    """Merge a partial LLM cluster result into *base* in-place.

    Themes with the same name have their keyword lists unioned (order preserved,
    duplicates dropped). Unknown themes are appended. Unclustered lists are unioned.
    """
    # Build index: theme name → position in base["themes"]
    base_index: dict[str, int] = {t["name"]: i for i, t in enumerate(base["themes"])}

    for theme in partial.get("themes", []):
        name = theme.get("name", "").strip()
        if not name:
            continue
        new_kws: list[str] = theme.get("keywords", [])
        if name in base_index:
            existing = base["themes"][base_index[name]]["keywords"]
            seen = set(existing)
            for kw in new_kws:
                if kw not in seen:
                    existing.append(kw)
                    seen.add(kw)
        else:
            base["themes"].append({"name": name, "keywords": list(new_kws)})
            base_index[name] = len(base["themes"]) - 1

    # Union unclustered lists
    existing_unc = set(base.get("unclustered", []))
    for kw in partial.get("unclustered", []):
        if kw not in existing_unc:
            base["unclustered"].append(kw)
            existing_unc.add(kw)


def _recover_partial_json(raw: str) -> dict | None:
    """
    Salvage complete theme objects from a response that was truncated mid-JSON.

    When the output token limit is hit, any theme objects that were fully serialised
    before the truncation point are still valid.  This function scans the partial
    JSON string incrementally, collecting complete ``{"name": ..., "keywords": [...]}``
    objects, and returns them as a minimal valid result dict.

    Returns None if no complete theme objects can be extracted (total parse failure).
    """
    themes: list[dict] = []
    decoder = json.JSONDecoder()

    # Locate the start of the themes array — everything before it is structure we skip.
    themes_marker = raw.find('"themes"')
    if themes_marker == -1:
        return None
    array_start = raw.find('[', themes_marker)
    if array_start == -1:
        return None

    pos = array_start + 1
    while pos < len(raw):
        # Advance past whitespace and comma separators between objects.
        while pos < len(raw) and raw[pos] in ' \t\n\r,':
            pos += 1
        if pos >= len(raw) or raw[pos] != '{':
            break  # Either end of array or start of truncated object — stop.
        try:
            obj, end_pos = decoder.raw_decode(raw, pos)
        except json.JSONDecodeError:
            break  # Truncation point — abandon remainder.
        if isinstance(obj, dict) and "name" in obj and "keywords" in obj:
            themes.append(obj)
        pos = end_pos

    if not themes:
        return None

    logger.warning(
        "build_vocabulary: partial recovery — salvaged %d complete theme(s) from truncated response",
        len(themes),
    )
    return {"themes": themes, "unclustered": []}


def _recover_partial_refinement_json(raw: str) -> dict | None:
    """
    Salvage complete theme-additions entries from a truncated refinement response.

    When the output token limit is hit mid-JSON, any ``"ThemeName": [...]`` pairs
    that were fully serialised before the cutoff are still valid.  This function
    scans the partial ``"additions": {...}`` dict incrementally and collects every
    complete key-value pair it can find before hitting truncation.

    Returns None if no complete entries can be extracted.
    """
    additions: dict[str, list[str]] = {}
    decoder = json.JSONDecoder()

    # Locate the opening brace of the additions object.
    additions_marker = raw.find('"additions"')
    if additions_marker == -1:
        return None
    obj_start = raw.find('{', additions_marker)
    if obj_start == -1:
        return None

    pos = obj_start + 1
    while pos < len(raw):
        # Skip whitespace and the comma that separates successive entries.
        while pos < len(raw) and raw[pos] in ' \t\n\r,':
            pos += 1
        if pos >= len(raw) or raw[pos] != '"':
            break  # Closing brace, end of string, or truncation before the key.
        # Decode the theme name (a JSON string).
        try:
            theme_name, name_end = decoder.raw_decode(raw, pos)
        except json.JSONDecodeError:
            break
        if not isinstance(theme_name, str):
            break
        # Advance past the colon separating key from value.
        colon_pos = raw.find(':', name_end)
        if colon_pos == -1:
            break
        val_pos = colon_pos + 1
        while val_pos < len(raw) and raw[val_pos] in ' \t\n\r':
            val_pos += 1
        if val_pos >= len(raw) or raw[val_pos] != '[':
            break  # Value is missing or truncated before the opening bracket.
        # Decode the keyword array.
        try:
            keywords, arr_end = decoder.raw_decode(raw, val_pos)
        except json.JSONDecodeError:
            break  # Array is truncated — stop here, don't salvage partial arrays.
        if isinstance(keywords, list):
            additions[theme_name] = [k for k in keywords if isinstance(k, str)]
        pos = arr_end

    if not additions:
        return None

    logger.warning(
        "build_vocabulary: refinement partial recovery — salvaged %d theme addition(s)",
        len(additions),
    )
    return {"additions": additions}


def _remediate_unclustered(
    merged: dict,
    llm: LLMClient,
    max_tokens: int,
    chunk_size: int,
    *,
    chunk_chars_override: int | None = None,
) -> None:
    """
    Assign unclustered keywords into existing themes where possible.

    Sends the unclustered list + current theme names to the LLM and asks it
    to place each keyword into one or more existing themes (or confirm it stays
    unclustered).  Modifies *merged* in place.  Unclustered keywords that the
    LLM cannot place are preserved in merged["unclustered"].

    Parameters
    ----------
    merged:
        The accumulated cluster result to update in place.
    llm:
        LLMClient instance to use for the remediation call(s).
    max_tokens:
        Max output tokens per LLM call.
    chunk_size:
        Hard-cap on keywords per remediation chunk (CLI ``--chunk-size``).
        ``0`` or negative disables the cap; smart sizing (N1) computes the
        actual count from ``llm.num_ctx``.
    chunk_chars_override:
        Optional per-mode override from ``extraction.yaml``; bypasses the
        num_ctx-derived budget for the smart-sizing computation.
    """
    unclustered = merged.get("unclustered", [])
    if not unclustered:
        logger.info("build_vocabulary: no unclustered keywords — skipping remediation pass")
        return

    theme_names = [t["name"] for t in merged.get("themes", [])]
    if not theme_names:
        logger.warning(
            "build_vocabulary: no themes exist — cannot remediate %d unclustered keywords",
            len(unclustered),
        )
        return

    logger.info(
        "build_vocabulary: remediating %d unclustered keywords against %d themes…",
        len(unclustered), len(theme_names),
    )

    # N1: smart-size the chunks; honor the CLI hard-cap when set.
    user_cap = chunk_size if chunk_size and chunk_size > 0 else None
    effective_chunk_size = _keywords_per_chunk(
        llm, unclustered,
        user_cap=user_cap,
        chunk_chars_override=chunk_chars_override,
    )
    chunks = _chunk_list(unclustered, effective_chunk_size)
    still_unclustered: list[str] = []
    # Rebuild index each time we enter this function so it reflects the
    # current merged["themes"] state.
    theme_index: dict[str, int] = {t["name"]: i for i, t in enumerate(merged["themes"])}
    _prompts = load_clustering_prompts()

    for i, chunk in enumerate(chunks, start=1):
        if len(chunks) > 1:
            logger.info(
                "build_vocabulary: remediation chunk %d/%d (%d keywords)…",
                i, len(chunks), len(chunk),
            )
        # C1 review: theme names and unclustered keywords are echoed back from
        # the merged vocabulary, which is built from user-controllable Zotero
        # keyword strings. Scrub role markers before rendering — these never
        # reached the main-loop's safe_chunk sanitization. Short strings →
        # default fence-stripping.
        safe_theme_names = [sanitize_for_prompt(name) for name in theme_names]
        safe_chunk = [sanitize_for_prompt(kw) for kw in chunk]
        raw = llm.complete(
            _prompts.remediation_system,
            _prompts.render_remediation_user(safe_theme_names, safe_chunk),
            max_tokens=max_tokens,
        )
        try:
            result = parse_llm_json(raw)
        except ValueError as exc:
            logger.warning(
                "build_vocabulary: remediation chunk %d/%d failed to parse (%s) — "
                "leaving %d keywords unclustered",
                i, len(chunks), exc, len(chunk),
            )
            still_unclustered.extend(chunk)
            continue

        for kw, assigned_themes in result.get("assignments", {}).items():
            for theme_name in assigned_themes:
                if theme_name not in theme_index:
                    logger.debug(
                        "build_vocabulary: remediation — unknown theme %r for kw %r, skipped",
                        theme_name, kw,
                    )
                    continue
                existing = merged["themes"][theme_index[theme_name]]["keywords"]
                if kw not in existing:
                    existing.append(kw)

        still_unclustered.extend(result.get("still_unclustered", []))

    n_placed = len(unclustered) - len(still_unclustered)
    logger.info(
        "build_vocabulary: remediation complete — %d placed, %d still unclustered",
        n_placed, len(still_unclustered),
    )
    merged["unclustered"] = still_unclustered


def _refine_clustering(
    merged: dict,
    llm: LLMClient,
    max_tokens: int = 32768,
    debug_output_path: Path | None = None,
) -> None:
    """
    Global cross-theme refinement pass.

    Sends the full merged clustering to the LLM and asks it to identify keywords
    that should appear in additional themes beyond their current placement.
    Only additions are applied — existing assignments are never removed.
    Modifies *merged* in place.

    Parameters
    ----------
    merged:
        The accumulated cluster result to update in place.
    llm:
        LLMClient instance to use for the refinement call.
    max_tokens:
        Max output tokens for the refinement LLM call.  Defaults to 32768 —
        a cloud-Ollama-safe positive cap that still accommodates the additions
        JSON for large vocabularies (150+ themes), which can easily exceed
        16 000 tokens.  Pass an explicit smaller value only when the calling
        context has a hard ceiling and you want a graceful truncation +
        partial-recovery path.
    debug_output_path:
        If provided, the raw LLM response is written to this path unconditionally
        (before any parsing attempt) so the caller can inspect truncation or
        unexpected content even when the pass succeeds.  Useful for diagnosing
        output size issues on large libraries.
    """
    if not merged.get("themes"):
        logger.info("build_vocabulary: no themes — skipping refinement pass")
        return

    logger.info("build_vocabulary: running global cross-theme refinement pass…")
    _prompts = load_clustering_prompts()
    # C1 review: the refinement prompt renders every theme name and keyword
    # string from the merged vocabulary (all user-controllable Zotero keywords)
    # raw. Sanitize the rendered prompt so a role marker in any keyword cannot
    # break out. Short strings → default fence-stripping.
    refinement_user = sanitize_for_prompt(_prompts.render_refinement_user(merged))

    # N1 smart-sizing awareness for refinement: estimate prompt cost and WARN
    # if it exceeds the model's safe input budget.  Refinement is by design a
    # single full-vocabulary call, so we cannot chunk-split here — we warn
    # loudly so the user knows to either (a) raise num_ctx_override, (b) shrink
    # the vocabulary, or (c) accept truncation.
    refinement_input_chars = len(refinement_user) + len(_prompts.refinement_system)
    ctx = getattr(llm, "num_ctx", None)
    if ctx:
        budget_chars = int((ctx * _SAFETY_FACTOR - _SYSTEM_PROMPT_RESERVE_TOKENS) * _CHARS_PER_TOKEN)
        if refinement_input_chars > budget_chars:
            logger.warning(
                "build_vocabulary: refinement prompt (%d chars) exceeds smart budget "
                "(%d chars at num_ctx=%d).  Output may truncate.  Consider raising "
                "num_ctx_override or shrinking the vocabulary.",
                refinement_input_chars, budget_chars, ctx,
            )
        else:
            logger.info(
                "build_vocabulary: refinement prompt %d chars / budget %d (num_ctx=%d) — OK",
                refinement_input_chars, budget_chars, ctx,
            )
    # ctx=None (e.g. refine_llm built with num_ctx=None) means "use full native context";
    # no budget check possible — proceed.

    raw = llm.complete(
        _prompts.refinement_system,
        refinement_user,
        max_tokens=max_tokens,
    )

    # Persist the raw response unconditionally so the caller can verify the
    # pass completed and diagnose truncation even when parsing succeeds.
    if debug_output_path is not None:
        try:
            debug_output_path.parent.mkdir(parents=True, exist_ok=True)
            debug_output_path.write_text(raw, encoding="utf-8")
            logger.info(
                "build_vocabulary: refinement raw response (%d chars) saved to %s",
                len(raw), debug_output_path,
            )
        except OSError as exc:
            logger.warning(
                "build_vocabulary: could not write refinement debug output: %s", exc
            )

    try:
        result = parse_llm_json(raw)
    except ValueError as exc:
        # Response may have been truncated.  Attempt to salvage whatever complete
        # "ThemeName": [...] entries were serialised before the cutoff.
        logger.warning(
            "build_vocabulary: refinement pass failed to parse (%s) — "
            "attempting partial recovery…",
            exc,
        )
        result = _recover_partial_refinement_json(raw)
        if result is None:
            logger.warning(
                "build_vocabulary: refinement partial recovery found nothing — "
                "skipping refinement pass"
            )
            return

    theme_index: dict[str, int] = {t["name"]: i for i, t in enumerate(merged["themes"])}
    n_added = 0
    for theme_name, new_kws in result.get("additions", {}).items():
        if theme_name not in theme_index:
            logger.debug(
                "build_vocabulary: refinement — unknown theme %r, skipped", theme_name
            )
            continue
        existing = merged["themes"][theme_index[theme_name]]["keywords"]
        existing_set = set(existing)
        for kw in new_kws:
            if kw not in existing_set:
                existing.append(kw)
                existing_set.add(kw)
                n_added += 1

    logger.info(
        "build_vocabulary: refinement complete — %d cross-theme keywords added", n_added
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_vocabulary(
    keywords: dict[str, list[str]],
    llm: LLMClient,
    output_path: Path = CONCEPTS_DRAFT_PATH,
    max_tokens: int = 16384,
    chunk_size: int = 0,
    remediate: bool = True,
    refine: bool = False,
    refine_llm: LLMClient | None = None,
    chunk_chars_override: int | None = None,
) -> dict:
    """
    Use the LLM to cluster canonical keywords into themes.

    Keywords are smart-chunked (N1, 2026-05-17): the chunk size is computed from
    the LLM's ``num_ctx`` so each prompt fills the available input budget without
    overrunning it.  All three passes (initial clustering, remediation, refinement)
    use the same sizing.  Pass ``chunk_size`` to enforce a HARD CAP (CLI
    ``--chunk-size``) — the smart sizing computes the natural maximum and
    ``chunk_size`` clamps it down further.

    After initial chunked clustering, two optional refinement passes are
    available:

    - *remediate* (default on): sends any unclustered keywords back to the LLM
      with the full list of identified theme names, asking it to assign each
      keyword to the closest existing theme.  Reduces leftover noise.

    - *refine* (default off): sends the complete merged clustering to the LLM
      in one call and asks it to identify cross-theme keyword assignments that
      were missed during per-chunk processing.  Useful when a keyword clearly
      belongs in two themes that were processed in different chunks.

    Parameters
    ----------
    keywords:
        Output of normalizer.normalise_keywords — {canonical: [variants]}.
    llm:
        Any LLMClient instance (OllamaClient in prod, MockLLMClient in tests).
        Used for chunked clustering and the remediation pass.
    output_path:
        Where to write concepts_draft.yaml. Defaults to config/concepts_draft.yaml.
    max_tokens:
        Max tokens per LLM response for the chunked clustering and remediation
        passes.  The refinement pass always uses max_tokens=32768 (positive cap,
        cloud-Ollama-safe) regardless of this value — see *refine_llm*.
    chunk_size:
        Hard cap on keywords per LLM call (CLI ``--chunk-size``).  ``0`` (default)
        or negative means "no cap — use smart sizing from num_ctx alone".  When
        provided, the effective chunk size is ``min(smart_size, chunk_size)``.
    remediate:
        If True (default), run _remediate_unclustered() after initial clustering.
    refine:
        If True (default False), run _refine_clustering() after remediation.
        Adds one extra LLM call over the full vocabulary — useful but slower.
    refine_llm:
        Optional separate LLMClient for the refinement pass.  The refinement
        prompt includes the full merged vocabulary; pass an OllamaClient with
        ``num_ctx=None`` here so the model uses its native context window for
        generation.  If None, the main *llm* is used.
    chunk_chars_override:
        Optional per-mode override from ``extraction.yaml build_vocabulary.chunk_chars``.
        Bypasses the num_ctx-derived budget when set.  Default None.

    Returns
    -------
    dict
        Parsed structure: {"themes": [...], "unclustered": [...]}.
        Also written to output_path as YAML.
    """
    canonical_list = sorted(keywords.keys())

    if not canonical_list:
        logger.warning("build_vocabulary: keyword list is empty — returning empty clusters")
        result: dict = {"themes": [], "unclustered": []}
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            yaml.dump(result, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
        return result

    # N1: smart-size the chunks; the CLI `--chunk-size` (if >0) is a hard cap.
    user_cap = chunk_size if chunk_size and chunk_size > 0 else None
    effective_chunk_size = _keywords_per_chunk(
        llm, canonical_list,
        user_cap=user_cap,
        chunk_chars_override=chunk_chars_override,
    )
    chunks = _chunk_list(canonical_list, effective_chunk_size)
    n_chunks = len(chunks)
    merged: dict = {"themes": [], "unclustered": []}
    _prompts = load_clustering_prompts()

    for i, chunk in enumerate(chunks, start=1):
        logger.info(
            "build_vocabulary: clustering chunk %d/%d (%d keywords)…",
            i, n_chunks, len(chunk),
        )
        # C1: Zotero keyword strings are user-controllable; a malicious tag
        # could carry ChatML/Llama role markers into the clustering prompt.
        # Keywords are short → default fence-stripping is correct here.
        safe_chunk = [sanitize_for_prompt(kw) for kw in chunk]
        raw = llm.complete(_prompts.system, _prompts.render_user(safe_chunk), max_tokens=max_tokens)
        try:
            partial = parse_llm_json(raw)
        except ValueError as parse_exc:
            # Response was likely truncated at the token limit.  Attempt to salvage
            # whatever complete theme objects were serialised before the cutoff.
            logger.warning(
                "build_vocabulary: chunk %d/%d JSON parse failed (%s) — "
                "attempting partial recovery…",
                i, n_chunks, parse_exc,
            )
            partial = _recover_partial_json(raw)
            if partial is None:
                logger.error(
                    "build_vocabulary: chunk %d/%d — no themes recoverable; "
                    "skipping chunk. If this recurs, reduce --chunk-size (try 30).",
                    i, n_chunks,
                )
                continue
        if "themes" not in partial:
            partial["themes"] = []
        if "unclustered" not in partial:
            partial["unclustered"] = []
        _merge_clusters(merged, partial)
        logger.info(
            "build_vocabulary: chunk %d/%d done — %d themes so far",
            i, n_chunks, len(merged["themes"]),
        )

    # Optional post-processing passes
    if remediate:
        _remediate_unclustered(
            merged, llm, max_tokens, chunk_size,
            chunk_chars_override=chunk_chars_override,
        )
    if refine:
        # Use a separate LLM (no num_ctx cap) if the caller provided one.
        # The refinement prompt is the full vocabulary — too large for the
        # num_ctx=8192 ceiling used during chunked clustering.
        _effective_refine_llm = refine_llm if refine_llm is not None else llm
        _refine_debug_path = output_path.with_name(
            output_path.stem + "_refinement_raw.txt"
        )
        _refine_clustering(
            merged,
            _effective_refine_llm,
            # max_tokens=32768: positive cap, cloud-Ollama-safe (num_predict=-1
            # returns 400 on cloud Ollama); sized well above the ~7k refinement prompt.
            debug_output_path=_refine_debug_path,
        )

    # Write draft YAML
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        yaml.dump(merged, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    logger.info(
        "build_vocabulary: wrote %s — %d themes, %d unclustered keywords",
        output_path, len(merged["themes"]), len(merged["unclustered"]),
    )
    return merged


def _pick_query_terms(theme_name: str, keywords: list[str], max_terms: int = 4) -> list[str]:
    """
    Pick a small set of representative search terms from a theme's keyword list.

    Preference order:
    1. 2–3 word phrases — specific enough to be meaningful in a database search.
    2. If fewer than 2 preferred candidates exist, fall back to the full list
       sorted by length (longer → more specific).
    3. If the keyword list is empty, return the theme name lowercased as a
       last-resort term.

    The selected terms are passed to clusters_to_topics_yaml() to construct an
    OR-joined query string.  They are intentionally chosen for recall over
    precision because the user is expected to review and tighten queries before
    production use.
    """
    preferred = [kw for kw in keywords if 2 <= len(kw.split()) <= 3]
    if preferred:
        # Sort by total length ascending — shorter phrases are more likely to
        # appear verbatim in paper metadata.
        return sorted(preferred, key=len)[:max_terms]
    if keywords:
        # Fallback: sort by length descending (longer = more specific).
        return sorted(keywords, key=len, reverse=True)[:max_terms]
    return [theme_name.lower()]


def clusters_to_topics_yaml(
    clusters: dict,
    databases: list[str] | None = None,
) -> str:
    """
    Render clustered themes as a ``topics.yaml``-compatible search entry list.

    Each theme in *clusters* becomes one search entry.  The query is constructed
    by selecting a small number of representative keywords from the theme via
    ``_pick_query_terms()`` and joining them with OR.  Multi-word terms are
    double-quoted for exact-phrase matching in PubMed/arXiv.

    The output is a YAML string with a header comment indicating it is
    auto-generated.  Write it to ``TOPICS_SUGGESTED_PATH`` and diff it against
    the live ``topics.yaml`` before deciding which entries to incorporate.

    Parameters
    ----------
    clusters:
        Parsed clustering result — ``{"themes": [...], "unclustered": [...]}``.
        Typically the return value of ``build_vocabulary()``.
    databases:
        List of database identifiers for every generated search entry.
        Defaults to ``["pubmed", "arxiv"]`` — the two databases supported
        without an API key in findpapers 0.6.x.

    Returns
    -------
    str
        YAML text ready to write to a file.
    """
    if databases is None:
        databases = ["pubmed", "arxiv"]

    searches: list[dict] = []
    for theme in clusters.get("themes", []):
        name = theme.get("name", "Unknown Theme")
        kws = theme.get("keywords", [])
        terms = _pick_query_terms(name, kws)
        # Quote multi-word phrases for exact-phrase matching; leave single
        # words unquoted so the database can apply its own stemming.
        quoted = [f'"{t}"' if " " in t else t for t in terms]
        query = " OR ".join(quoted)
        searches.append({
            "name": name,
            "query": query,
            "databases": list(databases),
        })

    data: dict = {"searches": searches}
    header = (
        "# Auto-generated by lit-monitor build-vocabulary — review before using.\n"
        "# Each entry corresponds to one vocabulary theme. Edit queries before production use.\n"
        "# Databases: pubmed and arxiv need no API key; scopus requires SCOPUS_API_KEY.\n"
    )
    return header + yaml.dump(
        data, default_flow_style=False, allow_unicode=True, sort_keys=False
    )


def map_keywords_to_themes(
    keywords: list[str],
    concepts: dict,
    threshold: float = 0.75,
) -> dict[str, list[str]]:
    """
    For each keyword, return the theme names it belongs to.
    Matching is exact string equality (lower-cased) against the keyword
    lists in each theme, with a rapidfuzz fallback for near-matches above
    the threshold.
    Parameters
    ----------
    keywords:
        List of keyword strings to map.
    concepts:
        Parsed concepts.yaml content — {"themes": [...], "unclustered": [...]}.
    threshold:
        Similarity threshold (0.0–1.0) for fuzzy fallback matching.
    Returns
    -------
    dict[str, list[str]]
        {keyword: [theme_name, ...]} — empty list means unmapped.
    """
    from rapidfuzz import fuzz
    threshold_score = threshold * 100  # rapidfuzz uses 0–100 scale
    themes = concepts.get("themes", [])

    # Build lookup: theme_name → set of lower-cased keywords
    theme_index: dict[str, list[str]] = {}
    for theme in themes:
        name = theme.get("name", "")
        kws = [k.lower().strip() for k in theme.get("keywords", [])]
        theme_index[name] = kws
    result: dict[str, list[str]] = {}
    for kw in keywords:
        kw_lower = kw.lower().strip()
        matched_themes: list[str] = []
        for theme_name, theme_kws in theme_index.items():
            # Exact match first
            if kw_lower in theme_kws:
                matched_themes.append(theme_name)
                continue
            # Fuzzy fallback
            for theme_kw in theme_kws:
                score = fuzz.ratio(kw_lower, theme_kw)
                if score >= threshold_score:
                    matched_themes.append(theme_name)
                    break
        result[kw] = matched_themes
    return result


def flag_unmapped(
    keywords: list[str],
    concepts: dict,
    threshold: float = 0.75,
) -> list[str]:
    """
    Return keywords that don't match any theme above the threshold.
    These are candidates for adding to existing themes or creating new ones.
    They are NOT silently dropped — callers should log or surface these
    for human review.
    Parameters
    ----------
    keywords:
        List of keyword strings to check.
    concepts:
        Parsed concepts.yaml content.
    threshold:
        Similarity threshold. Same value used in map_keywords_to_themes.
    Returns
    -------
    list[str]
        Keywords with no matching theme.
    """
    mapping = map_keywords_to_themes(keywords, concepts, threshold=threshold)
    unmapped = [kw for kw, themes in mapping.items() if not themes]
    if unmapped:
        logger.warning(
            "%d unmapped keywords (no theme match above threshold=%.2f): %s",
            len(unmapped), threshold, unmapped,
        )
    return unmapped
