"""
Discovery pipeline.
Discovery + ingestion in two blocks:
DISCOVERY BLOCK:
  1. run_searches() + run_researcher_searches() from topics/researchers config
  2. Filter DOIs already in state DB
  3. Embed each new candidate (against live ChromaDB)
  4. Sort by cosine similarity to existing knowledge base
  5. LLM rationale for top-K
  6. Write Literature/Digests/Discovery_{date}.md
  7. Store new DOIs as status='discovered'
INGESTION BLOCK:
  8. Poll Zotero for items added since the last recorded library version
     (stored as kv_store key 'zotero_library_version' in state DB).
     First run: stores baseline version and skips processing.
  9. For each new item with markdown attachment:
       - get_markdown_attachment → extract_paper (simple + complex phases)
       - write_paper_note → add_paper to ChromaDB → relink (new note only)
  10. Persist updated Zotero library version to state DB
dry_run=True: discovery block runs (search + rank + digest); NO state DB writes,
  NO notes written, NO `last_run_date` update.
screen_all=True: Send all new results to LLM rationale (not just top-K).
"""
from __future__ import annotations

import json
import logging
import time as _time
import uuid
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path
from typing import Any

import requests

from scripts.core.doi_resolver import resolve_doi
from scripts.core.item_router import detect_review
from scripts.core.strict_mode import strict_fallback
from scripts.llm.extractor import extract_paper
from scripts.llm.llm_client import RateLimitError
from scripts.llm.ranker import rank_papers
from scripts.obsidian_tools.relink import relink_note
from scripts.output.obsidian_writer import write_paper_note
from scripts.pipelines._ingest import index_embeddings_and_mark_phases
from scripts.pipelines.brain_build import (
    _check_item_quality,  # A2: metadata quality gate
    _extract_keywords,
    _llm_model_str,  # F15: handles single client and dict[int, LLMClient]
    _llm_provider_str,  # F15: handles single client and dict[int, LLMClient]
    _now,
    _paper_embed_text,
    _parse_year,
)
from scripts.search.researcher_tracker import run_researcher_searches
from scripts.search.search_runner import DEFAULT_DATABASES, filter_known_dois, run_searches
from scripts.search.semantic_scholar import enrich_paper

logger = logging.getLogger(__name__)
_DIGEST_TEMPLATE = """\
---
date: "{run_date}"
new_papers: {n_new}
top_similarity: {top_score:.3f}
---
# Discovery Digest — {run_date}
{n_new} new results found across {n_databases} databases.
Similarity threshold: >{sim_threshold:.2f}
## Top Results
{top_section}

## All New Results ({n_new})
{all_section}
---
*Generated by lit-monitor · {run_date}*
"""
@dataclass
class _RunSummary:
    new_papers_found: int = 0
    papers_ingested: int = 0
    papers_failed: int = 0
    digest_path: str = ""
    errors: list[str] = field(default_factory=list)
def run_discovery(
    config,
    state_db,
    zotero_client,
    embeddings_db,
    llm,
    dry_run: bool = False,
    screen_all: bool = False,
    top_k: int = 20,
    sim_threshold: float = 0.3,
) -> _RunSummary:
    """
    Run the discovery + ingestion pipeline.
    Parameters
    ----------
    config:
        Config object.
    state_db:
        StateDB instance.
    zotero_client:
        ZoteroClient instance.
    embeddings_db:
        EmbeddingsDB instance.
    llm:
        LLMClient instance.
    dry_run:
        If True, run discovery only; no writes to state DB or vault.
    screen_all:
        If True, generate LLM rationale for all results (not just top-K).
    top_k:
        Number of top results for LLM rationale (when screen_all is False).
    sim_threshold:
        Minimum similarity score for a result to be highlighted.
    Returns
    -------
    _RunSummary
    """
    summary = _RunSummary()
    run_id = str(uuid.uuid4())
    if not dry_run:
        state_db.start_run(run_id, "discovery")

    # A4: compute search window from last successful run date.
    # Cap at 90 days to avoid overwhelming databases after a long gap.
    _MAX_SINCE_DAYS = 90
    last_run_date_str = state_db.get_kv("last_run_date")
    if last_run_date_str:
        try:
            last_run = datetime.fromisoformat(last_run_date_str).date()
            since_days = min((date.today() - last_run).days + 1, _MAX_SINCE_DAYS)
            logger.warning("Search window: %d days (last run: %s)", since_days, last_run_date_str)
        except ValueError:
            since_days = 14
            logger.warning("Could not parse last_run_date %r — defaulting to 14 days", last_run_date_str)
    else:
        since_days = 14
        logger.warning("No last_run_date stored — defaulting search window to 14 days")

    # ----------------------------------------------------------------
    # Discovery block
    # ----------------------------------------------------------------
    try:
        raw_papers, search_errors = _run_discovery(config, since_days=since_days)
        summary.errors.extend(search_errors)
        # A4: advance date after successful discovery so subsequent runs compute
        # the correct search window.
        # H1: dry_run is supposed to be DB-read-only (per module docstring) — gate
        # the write so dry runs do not silently mutate kv_store.
        if not dry_run:
            state_db.set_kv("last_run_date", str(date.today()))
    except Exception as exc:
        logger.error("Discovery searches failed: %s", exc, exc_info=True)
        summary.errors.append(f"discovery: {exc}")
        raw_papers = []
    new_papers = filter_known_dois(raw_papers, state_db)
    summary.new_papers_found = len(new_papers)
    logger.warning("Discovery: %d new results after dedup", len(new_papers))
    # Rank by similarity
    ranked = rank_papers(
        new_papers,
        embeddings_db,
        llm,
        top_k=len(new_papers) if screen_all else top_k,
    )
    # L2: fetch recent runs for Pipeline Run Summary prepended to digest
    recent_runs = state_db.get_recent_runs(limit=5) if not dry_run else []
    # Write digest
    digest_path = _write_digest(
        ranked, config, sim_threshold, dry_run=dry_run, recent_runs=recent_runs,
    )
    summary.digest_path = digest_path
    # Persist discovered papers
    if not dry_run:
        for paper in new_papers:
            doi = paper.get("doi", "")
            if doi:
                state_db.upsert_paper({
                    "doi": doi,
                    "title": paper.get("title", ""),
                    "authors": paper.get("authors", []),
                    "year": paper.get("year", 0),
                    "status": "discovered",
                    "source_type": "paper",
                    "first_seen_date": str(date.today()),
                    "similarity_score": paper.get("similarity_score", 0.0),
                    "llm_rationale": paper.get("llm_rationale", ""),
                    "last_updated": _now(),
                })
    # ----------------------------------------------------------------
    # Ingestion block
    # ----------------------------------------------------------------
    if not dry_run:
        _run_ingestion(
            config=config,
            state_db=state_db,
            zotero_client=zotero_client,
            embeddings_db=embeddings_db,
            llm=llm,
            summary=summary,
            run_id=run_id,
        )
        state_db.finish_run(
            run_id,
            status="complete",
            processed=summary.papers_ingested,
            failed=summary.papers_failed,
            errors=summary.errors,
        )
    return summary

# ---------------------------------------------------------------------------
# Discovery helpers
# ---------------------------------------------------------------------------
def _run_discovery(
    config, since_days: int = 14
) -> tuple[list[dict[str, Any]], list[str]]:
    """Run topic + researcher searches and merge results.

    Parameters
    ----------
    since_days:
        Search window in days from today. Computed from the stored
        'last_run_date' kv_store entry so that skipped weeks are
        automatically caught up on the next run.
    """
    papers: list[dict[str, Any]] = []
    errors: list[str] = []
    try:
        papers.extend(run_searches(config, since_days=since_days))
    except Exception as exc:
        logger.warning("Topic searches failed: %s", exc)
        errors.append(f"topic_search: {exc}")
    try:
        papers.extend(run_researcher_searches(config, since_days=since_days))
    except Exception as exc:
        logger.warning("Researcher searches failed: %s", exc)
        errors.append(f"researcher_search: {exc}")
    # Deduplicate by DOI across both search types
    seen: set[str] = set()
    deduped: list[dict[str, Any]] = []
    for p in papers:
        doi = p.get("doi", "")
        if doi and doi not in seen:
            seen.add(doi)
            deduped.append(p)
        elif not doi:
            deduped.append(p)  # keep no-DOI results (filtered later)
    return deduped, errors
def _write_digest(
    ranked: list[dict[str, Any]],
    config,
    sim_threshold: float,
    dry_run: bool = False,
    n_databases: int | None = None,
    recent_runs: list[dict] | None = None,
) -> str:
    """
    Render and write the discovery digest note. Returns the note path.
    n_databases defaults to len(DEFAULT_DATABASES) + 1 (for S2 supplementary search).
    recent_runs: if provided, a Pipeline Run Summary section is prepended (L2).
    """
    run_date = str(date.today())
    vault_path = Path(config.obsidian.vault_path)
    digests_folder = vault_path / config.obsidian.digests_folder
    if not dry_run:
        digests_folder.mkdir(parents=True, exist_ok=True)
    top_results = [p for p in ranked if p.get("similarity_score", 0.0) >= sim_threshold]
    top_score = ranked[0].get("similarity_score", 0.0) if ranked else 0.0
    top_section = _format_paper_list(top_results[:20], include_rationale=True)
    all_section = _format_paper_list(ranked, include_rationale=False)
    _n_db = n_databases if n_databases is not None else len(DEFAULT_DATABASES) + 1
    content = _DIGEST_TEMPLATE.format(
        run_date=run_date,
        n_new=len(ranked),
        top_score=top_score,
        n_databases=_n_db,
        sim_threshold=sim_threshold,
        top_section=top_section,
        all_section=all_section,
    )
    # L2: prepend Pipeline Run Summary if recent_runs provided
    if recent_runs:
        content = _format_pipeline_run_summary(recent_runs) + "\n---\n\n" + content
    digest_path = digests_folder / f"Discovery_{run_date}.md"

    if not dry_run:
        digest_path.write_text(content, encoding="utf-8")
        logger.warning("Wrote discovery digest: %s", digest_path)
    return str(digest_path)


def _format_pipeline_run_summary(recent_runs: list[dict]) -> str:
    """Format a Pipeline Run Summary section from run_log entries (L2)."""
    lines = ["## Pipeline Run Summary", ""]
    for run in recent_runs:
        run_type = run.get("run_type", "?")
        started = (run.get("started_at") or "")[:16].replace("T", " ")
        status = run.get("status", "?")
        processed = run.get("papers_processed", 0)
        failed = run.get("papers_failed", 0)
        lines.append(
            f"- **{run_type}** {started} — {status} "
            f"({processed} processed, {failed} failed)"
        )
    return "\n".join(lines) + "\n"
def _format_paper_list(
    papers: list[dict[str, Any]], include_rationale: bool
) -> str:
    if not papers:
        return "*No results.*"
    lines = []
    for p in papers:
        doi = p.get("doi", "")
        title = p.get("title", "")
        authors = p.get("authors", [])
        year = p.get("year", "")
        score = p.get("similarity_score", 0.0)
        rationale = p.get("llm_rationale", "")
        author_str = ", ".join(authors[:3])
        if len(authors) > 3:
            author_str += " et al."
        doi_link = f"https://doi.org/{doi}" if doi else ""
        line = f"- **{title}** · {author_str} ({year}) · score: {score:.3f}"
        if doi_link:
            line += f" · [DOI]({doi_link})"
        if include_rationale and rationale:
            line += f"\n  > {rationale}"
        lines.append(line)
    return "\n".join(lines)
# ---------------------------------------------------------------------------
# Ingestion helpers
# ---------------------------------------------------------------------------
def _run_ingestion(
    config,
    state_db,
    zotero_client,
    embeddings_db,
    llm,
    summary: _RunSummary,
    run_id: str,
) -> None:
    """
    Poll Zotero for new items and ingest papers with PDFs.

    Version-based polling: reads 'zotero_library_version' from the state DB
    kv_store. On first invocation (no stored version) the current library
    version is saved as a baseline and the function returns without processing
    — the full library is already handled by brain-build. Subsequent calls
    fetch only items added after the stored version and update the stored
    version on completion.
    """
    from scripts.core.zotero_client import ZoteroClient
    # Version-based Zotero polling — compare against last-seen library version.
    # On the first run there is no baseline; store the current version and skip
    # processing (the full library is already handled by brain-build).
    last_version_str = state_db.get_kv("zotero_library_version")
    if last_version_str is None:
        current_version = zotero_client.get_current_version()
        state_db.set_kv("zotero_library_version", str(current_version))
        logger.warning("First discovery run: baseline Zotero version %d stored", current_version)
        return
    last_version = int(last_version_str)
    try:
        new_items = zotero_client.get_items_since(last_version)
    except Exception as exc:
        logger.warning("Zotero poll failed: %s", exc)
        return
    logger.warning("Zotero poll: %d new items since version %d", len(new_items), last_version)
    consecutive_429 = 0  # V-9: abort after 3 consecutive rate-limit hits
    _topics_batch: list[tuple[str, list[str]]] = []  # M4: (doi, discovered_topics) pairs
    for item in new_items:
        data = item.get("data", {})
        doi = (data.get("DOI") or "").strip() or None
        zotero_key = item.get("key", "")
        title = data.get("title", "")
        if not doi:
            # D2: try CrossRef before giving up — ZoteroClient is already
            # imported at the top of this function (line: from scripts.core…).
            _authors = ZoteroClient.extract_authors(data)
            doi = resolve_doi(
                title, _authors, _parse_year(data.get("date", ""))
            ) or None
            if not doi:
                logger.debug("New Zotero item %s has no DOI — skipping", zotero_key)
                continue
            logger.debug(
                "CrossRef resolved DOI for new item %s (%s): %s",
                zotero_key, title[:60], doi,
            )

        # A2: metadata quality gate — skip items with empty titles (and warn on
        # absent authors / abstracts) before doing any expensive work.
        ok, reason = _check_item_quality(data)
        if not ok:
            logger.debug("Quality filter: skipping new item %s (%r) — %s", zotero_key, title[:60], reason)
            continue

        # A3: resume check — if a previous run fully processed this item (e.g.
        # ingestion partially completed then was restarted), skip it now.
        progress = state_db.get_brain_build_progress(zotero_key)
        if progress and progress.get("fully_complete"):
            logger.debug("Ingestion resume: %s already fully complete — skipping", doi)
            continue

        # Paper-status dedup: skip items already processed by brain-build or a
        # prior complete ingestion run.
        existing = state_db.get_paper(doi)
        if existing and existing.get("status") not in (None, "discovered"):
            continue

        # A3: register this item in the progress table before doing any work
        # so a crash mid-item is recoverable on the next run.
        state_db.upsert_brain_build_progress(zotero_key, doi)

        try:
            # M1: read markdown attachment from Zotero local storage.
            fulltext = zotero_client.get_markdown_attachment(zotero_key)
            if fulltext is None:
                logger.debug(
                    "No markdown attachment for new item %s — skipping "
                    "(attach a .md file in Zotero to enable extraction)",
                    doi,
                )
                continue
            ocr_heavy = False  # markdown attachments are never OCR-heavy
            authors = ZoteroClient.extract_authors(data)
            year = _parse_year(data.get("date", ""))
            journal = data.get("publicationTitle", "")
            abstract = data.get("abstractNote", "") or ""
            keywords = _extract_keywords(data)
            # L1: pre-extraction S2 enrichment (mirrors brain_build H3/H4).
            # Enrichment happens before extract_paper so detect_review() can
            # set the correct source_type on the first DB write.
            # H1: wrap so a transient S2 outage doesn't waste LLM tokens by
            # marking the paper failed; narrow exception list mirrors
            # brain_build for cross-pipeline consistency.
            try:
                s2_data = enrich_paper(doi)
            except (
                requests.exceptions.RequestException,
                ConnectionError,
                TimeoutError,
                json.JSONDecodeError,
                RuntimeError,
            ) as exc:
                logger.warning("S2 enrichment failed for %s (non-fatal): %s", doi, exc)
                s2_data = {}
            s2_pub_types = s2_data.get("s2_publication_types") if s2_data else None
            source_type = "paper"
            if detect_review(s2_pub_types, title=title, abstract=abstract, journal=journal):
                logger.debug("detect_review: classifying %s as review article", doi)
                source_type = "review"
            existing_extraction = state_db.get_extraction_json(doi) or {}
            # M3: determine which phases still need running based on progress row.
            _prog = state_db.get_brain_build_progress(zotero_key) or {}
            phases_needed: list[str] = []
            if not _prog.get("simple_complete"):
                phases_needed.append("simple")
            if not _prog.get("complex_complete"):
                phases_needed.append("complex")
            if not phases_needed:
                phases_needed = ["simple", "complex"]
            # M5: forward per-mode chunk_chars from extraction.yaml to simple phase.
            _ing_cfg = getattr(config, "ingestion", None)
            _chunk_chars = getattr(_ing_cfg, "chunk_chars", None)
            extraction = extract_paper(
                fulltext,
                llm,
                content_type=source_type,
                ocr_heavy=ocr_heavy,
                phases=tuple(phases_needed),
                existing_extraction=existing_extraction if existing_extraction else None,
                chunk_chars_override=int(_chunk_chars) if isinstance(_chunk_chars, (int, float)) else None,
            )
            # Merge S2 data into extraction so it's persisted in the same upsert.
            if s2_data:
                extraction.update(s2_data)
            # Audit R28 fix: defer phase marking until AFTER the paper-level
            # embed has succeeded.  Marking here would leave the paper stuck
            # at fully_complete=1 + status='error' if add_paper raises, and a
            # subsequent --resume would silently skip the retry.
            _phases_to_mark = [
                phase for phase in phases_needed
                if f"_{phase}_error" not in extraction
            ]

            # H1: persist the extraction payload but defer the status flip until
            # after the embed step succeeds.  Pre-fix, status='extraction_complete'
            # was written here and an add_paper failure would leave the row in a
            # 'looks done but has zero embeddings' state that --resume skipped.
            state_db.upsert_paper({
                "doi": doi,
                "title": title,
                "authors": authors,
                "year": year,
                "journal": journal,
                "zotero_key": zotero_key,
                "source_type": source_type,
                "extraction_json": json.dumps(extraction),
                "extraction_provider": _llm_provider_str(llm),
                "extraction_model": _llm_model_str(llm),
                "keywords_json": keywords,
                "first_seen_date": str(date.today()),
                "last_updated": _now(),
            })
            # Assign vocabulary themes from Zotero tags (B2).
            from scripts.vocabulary.normalizer import assign_themes
            themes = assign_themes(keywords)
            paper_record = {
                "doi": doi,
                "title": title,
                "authors": authors,
                "year": year,
                "journal": journal,
                "zotero_key": zotero_key,
                "first_seen_date": str(date.today()),
                "keywords": keywords,
                "themes": themes,
                "tracked_author": item.get("tracked_author", False),
                "fulltext_analyzed": True,
                # N8d: pass actual provider/model so the template doesn't fall
                # back to the (incorrect) global config attribute.
                "extraction_provider": _llm_provider_str(llm),
                "extraction_model": _llm_model_str(llm),
            }
            note_path = write_paper_note(paper_record, extraction, config)
            note_title = Path(note_path).stem
            embed_text = _paper_embed_text(title, abstract, extraction)
            # Each ingested item embeds into ChromaDB here — this is the "embeddings grow
            # on every run" mechanic the README leans on.
            chunks: list = []
            if fulltext:
                try:
                    from scripts.core.chunker import chunk_markdown
                    from scripts.core.markdown_processor import strip_end_matter
                    chunks = chunk_markdown(strip_end_matter(fulltext), doi)
                except Exception as exc:
                    logger.warning("Chunking failed for %s (non-fatal): %s", doi, exc)
            # R28: helper centralises add_paper + add_chunks + deferred phase marks.
            embed_ok, embed_err = index_embeddings_and_mark_phases(
                doi=doi,
                zotero_key=zotero_key,
                fulltext=embed_text,
                paper_metadata={"source_type": "paper", "title": title, "year": year},
                chunks=chunks,
                state_db=state_db,
                embeddings_db=embeddings_db,
                phases_to_mark=tuple(_phases_to_mark),
                logger=logger,
            )
            if not embed_ok:
                # Skip downstream work (state flag, relink) so the paper isn't
                # falsely marked complete; outer except will mark it failed.
                raise RuntimeError(embed_err)
            # H1: single authoritative status flip now that the embed step
            # succeeded — combined with the note path + embeddings flag write.
            state_db.upsert_paper({
                "doi": doi,
                "status": "extraction_complete",
                "note_title": note_title,
                "note_path": note_path,
                "embeddings_indexed": 1,
                "last_updated": _now(),
            })
            # Relink this note only
            try:
                relink_note(note_path, embeddings_db, state_db, config=config)
            except Exception as exc:
                logger.warning("Relink failed for %s: %s", doi, exc)

            # M4: collect discovered_topics for end-of-run vocabulary merge.
            _raw_topics = extraction.get("discovered_topics")
            if isinstance(_raw_topics, list) and _raw_topics:
                _topics_batch.append(
                    (doi, [str(t) for t in _raw_topics if t and isinstance(t, str)])
                )
            summary.papers_ingested += 1
            consecutive_429 = 0
            logger.debug("Ingested new paper: %s", doi)
        except RateLimitError as exc:
            # V-9: exponential back-off; abort after 3 consecutive hits.
            consecutive_429 += 1
            logger.warning(
                "Rate limit hit on %s (consecutive: %d): %s",
                doi, consecutive_429, exc,
            )
            if consecutive_429 >= 3:
                logger.error(
                    "Rate limit persists after %d consecutive hits — "
                    "aborting ingestion cleanly. "
                    "Quota should reset shortly; the next run will resume.",
                    consecutive_429,
                )
                # M1: mirror brain_build — record rate_limited status and exit
                # with non-zero code so cron logs are honest. Paper is NOT
                # marked error; next run will retry via Zotero poll.
                state_db.finish_run(
                    run_id,
                    status="rate_limited",
                    processed=summary.papers_ingested,
                    failed=summary.papers_failed,
                    errors=summary.errors,
                )
                raise SystemExit(2)
            wait = 60 * (2 ** (consecutive_429 - 1))
            logger.warning("Sleeping %ds before next paper", wait)
            _time.sleep(wait)
            # Paper not marked error — next run will retry via Zotero poll.
        except Exception as exc:
            consecutive_429 = 0
            logger.error("Ingestion failed for %s: %s", doi, exc, exc_info=True)
            summary.papers_failed += 1
            summary.errors.append(f"{doi}: {exc}")
    # Persist current library version so the next run only fetches newer items
    try:
        current_version = zotero_client.get_current_version()
        state_db.set_kv("zotero_library_version", str(current_version))
        logger.debug("Updated Zotero library version to %d", current_version)
    except Exception as exc:
        logger.warning("Could not update Zotero library version: %s", exc)

    # M4: append novel discovered_topics to topics.yaml and concepts.yaml.
    if _topics_batch:
        try:
            from scripts.vocabulary.topic_merger import merge_discovered_topics
            merged = merge_discovered_topics(_topics_batch)
            if merged:
                logger.warning(
                    "M4 vocabulary merge: %d novel topic(s) appended — %s",
                    len(merged), merged,
                )
        except Exception as exc:
            strict_fallback(
                logger,
                f"M4 vocabulary merge failed: {exc}. "
                "discovered_topics from this run were not appended to topics.yaml.",
                exc,
            )
