"""Guard test for the P5 dead-CSS cleanup on feat/webui-shoelace.

This pins a SPECIFIC set of CSS selectors that were removed because they were
provably unreferenced (superseded during P0–P5: old top-nav → app-shell sidebar,
hand-rolled modal → ``<sl-dialog>``, hand-rolled progress bar → ``<sl-progress-bar>``,
``.hero`` → ``.lm-hero``, settings rail removed from template, etc.).

Each removed selector must be absent from BOTH:
  * ``site.css`` (the rule is gone — verified by the selector token), AND
  * every template + ``site.js`` (it really is unused — nothing renders it).

This prevents accidental re-introduction of dead CSS and is the RED→GREEN guard:
restore any removed rule into ``site.css`` and ``test_removed_selectors_absent_from_css``
fails.

Selectors deliberately KEPT (false positives the audit had to exclude — they ARE
used, often via dynamic class composition) are NOT listed here:
  * ``.log-INFO`` / ``.log-WARNING`` / ``.log-ERROR`` / ``.log-DEBUG`` /
    ``.log-CRITICAL`` — generated by ``routes/sse.py`` via ``log-{level}``.
  * ``.degraded`` / ``.misconfigured`` / ``.unconfigured`` — health-badge status
    words rendered by ``routes/health.py`` into ``class="status-badge {{ status }}"``.
  * ``.htmx-request`` — HTMX-internal class added at request time.
  * ``.inline-check`` — still used in ``dev/index.html``.
  * ``.progress-block`` — still used in ``brain_build/index.html`` (only the
    ``.progress-bar`` / ``.progress-fill`` / ``.progress-label`` siblings were dead).
  * ``.app-rail`` / ``.btn-cta`` — KEPT (active app-shell / brand scaffolding with
    no current consumer; conservative "when in doubt, keep").
"""

import re
from pathlib import Path

# --- The exact selectors removed by this cleanup (the constant under guard). ---
# Each entry is the bare class/id name (no leading '.' or '#'); the type is in the
# second column so the absence-from-templates check can scope precisely.
REMOVED_CLASSES: tuple[str, ...] = (
    "failed-block",       # orphaned brain-build error block
    "modal",              # hand-rolled modal → <sl-dialog> (P1)
    "modal-backdrop",     # ditto
    "modal-body",         # ditto
    "navgroup",           # old top-nav → app-shell sidebar (P0)
    "navgroup-label",     # ditto
    "navmenu",            # ditto
    "topnav",             # ditto (incl. .topnav-inner / .topnav .brand / .topnav nav)
    "topnav-inner",       # ditto
    "hero",               # → .lm-hero (P3)
    "checkbox-inline",    # unused (only .inline-check survives)
    "checkbox-row",       # unused
    "status-grid",        # setup completion now uses .routes-table
    "settings-rail",      # explicitly removed from template (P2)
    "rate-btn",           # rating buttons → <sl-button> (Bundle H)
    "progress-bar",       # hand-rolled bar → <sl-progress-bar>
    "progress-fill",      # ditto
    "progress-label",     # ditto
)
REMOVED_IDS: tuple[str, ...] = (
    "latest-run-summary",  # P3.1 last-run card consolidated
)

_HERE = Path(__file__).resolve()
# tests/unit/test_css_no_orphans.py → repo root is three parents up.
_ROOT = _HERE.parents[2]
_STATIC = _ROOT / "lit_monitor" / "server" / "static"
_CSS = (_STATIC / "site.css").read_text()
_TEMPLATES = _ROOT / "lit_monitor" / "server" / "templates"


def _selector_in_css(token: str, sigil: str) -> bool:
    """True if ``site.css`` still defines a rule for ``{sigil}{token}``.

    Matches the selector token preceded by its sigil and NOT followed by an
    identifier char — so ``.modal`` does not match ``.modal-path`` (a kept class).
    """
    pattern = re.escape(sigil + token) + r"(?![A-Za-z0-9_-])"
    return re.search(pattern, _CSS) is not None


def _usage_corpus() -> str:
    """All templates + every static .js file, concatenated."""
    parts: list[str] = []
    for p in _TEMPLATES.rglob("*"):
        if p.is_file():
            parts.append(p.read_text(errors="ignore"))
    for js in _STATIC.rglob("*.js"):
        # Skip vendored third-party JS (Shoelace) — its source contains tokens
        # like "modal" / "progress-bar" that are unrelated to our CSS classes.
        if "vendor" in js.parts:
            continue
        parts.append(js.read_text(errors="ignore"))
    return "\n".join(parts)


_USAGE = _usage_corpus()


def _token_used(token: str) -> bool:
    """True if the bare ``token`` appears as a whole word in templates/js."""
    pattern = r"(?<![A-Za-z0-9_-])" + re.escape(token) + r"(?![A-Za-z0-9_-])"
    return re.search(pattern, _USAGE) is not None


def test_removed_selectors_absent_from_css():
    """Every removed selector's rule is gone from site.css (RED→GREEN guard)."""
    still_present = [f".{c}" for c in REMOVED_CLASSES if _selector_in_css(c, ".")]
    still_present += [f"#{i}" for i in REMOVED_IDS if _selector_in_css(i, "#")]
    assert not still_present, (
        f"these selectors were supposed to be removed but a rule still "
        f"defines them in site.css: {still_present}"
    )


def test_removed_selectors_unused_in_templates_and_js():
    """The removed selectors really are unreferenced — nothing renders them.

    Pins the cleanup's premise: if a template/JS re-introduces one of these
    classes, this fails and forces re-adding the CSS (or renaming the class).
    """
    reintroduced = [t for t in (*REMOVED_CLASSES, *REMOVED_IDS) if _token_used(t)]
    assert not reintroduced, (
        f"a removed selector was re-introduced into a template or site.js "
        f"(it now has no CSS rule): {reintroduced}"
    )
